[[redirects]]
  from = "/"
  to = "/overview/introduction/"
  status = 302

[[redirects]]
  from = "/overview/"
  to = "/overview/introduction/"
  status = 302

[[redirects]]
  from = "/api/gateways"
  to = "/api/gateways/index.json"
  status = 200

[[redirects]]
  from = "/api/delivery-models"
  to = "/api/delivery-models/index.json"
  status = 200

[[redirects]]
  from = "/api/gateway-capabilities"
  to = "/api/gateway-capabilities/index.json"
  status = 200

[[redirects]]
  from = "/api/platform-capabilities"
  to = "/api/platform-capabilities/index.json"
  status = 200

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Methods = "GET"
    Access-Control-Max-Age = "86400"
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/vnd.siren+json; charset=UTF-8"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"