[[redirects]]
  from = "/"
  to = "/overview/introduction/"
  status = 302

[[redirects]]
  from = "/overview/"
  to = "/overview/introduction/"
  status = 302

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Methods = "GET"
    Access-Control-Max-Age = "86400"
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/vnd.siren+json; charset=UTF-8"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"